version: '3.9'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - ${HTTP_PORT}:${HTTP_PORT}
        - ${HTTPS_PORT}:${HTTPS_PORT}
      #restart: always
      volumes:
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./config/nginx/no_ssl/:/etc/nginx/conf.d/:ro
      environment:
        HTTP_PORT: ${HTTP_PORT}
        HTTPS_PORT: ${HTTPS_PORT}
        TZ: ${TIME_ZONE}
