version: '3.9'

services:
  peresvet:
    container_name: ws_peresvet_debug
    build:
      context: .
      dockerfile: Docker/Dockerfile.peresvet

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --ws-ping-interval 10 --ws-ping-timeout 10

    volumes:
      - ./src/:/usr/src/
    ports:
      - 8002:8000
    environment:
      PRS_LOG_LEVEL: ${PRS_LOG_LEVEL}
      TZ: ${TIME_ZONE}
      LDAP_HOST: ws_ldap
      LDAP_PORT: ${LDAP_PORT}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_BASE_NODE: ${LDAP_BASE_NODE}
