version: '3.9'

services:
  peresvet:
    depends_on:
      - ldap_test
      - victoriametrics
    environment:
      PRS_LOG_LEVEL: DEBUG
      LDAP_HOST: ldap_test

  ldap_test:
    container_name: ldap_test
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    ports:
      - 3890:389
      - 6360:636
    environment:
      TZ: ${TIME_ZONE}
