version: '3.9'

services:
  grafana:
      container_name: grafana
      build:
        context: .
        dockerfile: Docker/Dockerfile.grafana
      ports:
        - 3000:3000
      environment:
        TZ: ${TIME_ZONE}
