version: '3.9'

services:
  peresvet:
    container_name: peresvet
    build:
      context: .
      dockerfile: Docker/Dockerfile.peresvet

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port ${HTTP_PORT} --ws-ping-interval 10 --ws-ping-timeout 10

    volumes:
      - ./src/:/usr/src/
    expose:
      - ${HTTP_PORT}
    depends_on:
      - ldap

    environment:
      PRS_LOG_LEVEL: ${PRS_LOG_LEVEL}
      TZ: ${TIME_ZONE}
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_BASE_NODE: ${LDAP_BASE_NODE}

  ldap:
    container_name: ldap
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    environment:
      TZ: ${TIME_ZONE}
