version: '3.9'

services:
  peresvet:
    container_name: peresvet
    build: 
      context: .
      dockerfile: Docker/Dockerfile.peresvet
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/
    ports:
      - 8002:8000
    depends_on:
      - ldap
      - victoriametrics
    environment:
      PRS_LOG_LEVEL: ${PRS_LOG_LEVEL}
      TZ: ${TIME_ZONE} 

  ldap:
    container_name: ldap
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    restart: always
    ports:
      - 389:389
      - 636:636
    environment:
      TZ: ${TIME_ZONE}
  
  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: vm
    restart: always
    ports:
      - 8428:8428
    volumes:
      - ./vm-data:/victoria-metrics-data
    environment:
      TZ: ${TIME_ZONE}

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      TZ: ${TIME_ZONE}