version: '3.9'

services:
  nginx:
      ports:
        - ${HTTP_PORT}:${HTTP_PORT}
        - ${HTTPS_PORT}:${HTTPS_PORT}
      #restart: always
      volumes:
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./config/nginx/ssl/:/etc/nginx/conf.d/
        - ./tls/servers/${SRV_NAME}/:/etc/nginx/ssl/server/
        - ./tls/rootCA/:/etc/nginx/ssl/root/
      environment:
        HTTP_PORT: ${HTTP_PORT}
        HTTPS_PORT: ${HTTPS_PORT}
        TZ: ${TIME_ZONE}
