version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Docker/Dockerfile.peresvet
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000

  ldap:
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    restart: always
  