version: '3.9'

services:
  peresvet:
    build: 
      context: .
      dockerfile: Docker/Dockerfile.peresvet
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    depends_on:
      - ldap
      - victoriametrics
    environment:
      LDAP_URI: ${LDAP_URI}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}

  ldap:
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    restart: always
    ports:
      - 389:389
      - 636:636
  
  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: vm
    restart: always
    ports:
      - 8428:8428
    volumes:
      - ./vm-data:/victoria-metrics-data

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000