version: '3.9'

services:
  peresvet:
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port ${HTTPS_PORT} --ssl-keyfile /usr/certs/${SRV_NAME}/${SRV_NAME}.key --ssl-certfile /usr/certs/${SRV_NAME}/${SRV_NAME}.crt --ssl-ca-certs /usr/certs/rootCA/rootCA.crt --ssl-cert-reqs ${CERT_REQUIRED} --ws-ping-interval 10 --ws-ping-timeout 10

    volumes:
      - ./src/:/usr/src/
      - ./tls/rootCA/rootCA.crt:/usr/certs/rootCA/rootCA.crt
      - ./tls/servers/${SRV_NAME}/${SRV_NAME}.crt:/usr/certs/${SRV_NAME}/${SRV_NAME}.crt
      - ./tls/servers/${SRV_NAME}/${SRV_NAME}.key:/usr/certs/${SRV_NAME}/${SRV_NAME}.key
    expose:
      - ${HTTPS_PORT}
