version: '3'

services:
  nginx:
      image: nginx:latest
      container_name: nginx_load_test
      ports:
        - ${HTTP_PORT}:${HTTP_PORT}
      volumes:
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./config/nginx/no_ssl/default.conf.template:/etc/nginx/templates/default.conf.template:rw,cached
      environment:
        HTTP_PORT: ${HTTP_PORT}
        HTTPS_PORT: ${HTTPS_PORT}
        TZ: ${TIME_ZONE}
      depends_on:
        - peresvet

  peresvet:
    build:
      context: .
      dockerfile: Docker/Dockerfile.peresvet

    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port ${HTTP_PORT} --ws-ping-interval 10 --ws-ping-timeout 10

    volumes:
      - ./src/:/usr/src/
    depends_on:
      - ldap
      - postgres
    environment:
      PRS_LOG_LEVEL: ${PRS_LOG_LEVEL}
      TZ: ${TIME_ZONE}
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_BASE_NODE: ${LDAP_BASE_NODE}

  ldap:
    container_name: ldap
    build:
      context: .
      dockerfile: Docker/Dockerfile.ldap
    environment:
      TZ: ${TIME_ZONE}
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
    ports:
      - ${LDAP_PORT}:${LDAP_PORT}

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
      TZ: ${TIME_ZONE}
    ports:
      - 8010:80
