version: '3.9'

services:
  tags_all:
    hostname: tags_all
    build:
      context: ../..
      dockerfile: docker/debug/docker-files/tags_model_crud/Dockerfile.tags_model_crud.debug

    command: uvicorn src.services.tags.model_crud.tags_model_crud_svc:app --reload
    environment:
      TZ: ${TIME_ZONE}
