version: '3.9'
services:
  rabbitmq:
    image: mpc/peresvet_rabbitmq:0.4-arm64
    hostname: ${HOST_RABBIT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
      TZ: ${TIME_ZONE}
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
