version: '3'

services:
  locust_master:
    build:
      context: ../..
      dockerfile: docker/docker-files/locust/Dockerfile.locust
    volumes:
      - ../../tests/load/:/mnt/locust/
    ports:
     - 8089:8089
    command: -f /mnt/locust --class-picker --master -H http://tags_load_tests:81

  locust_worker:
    build:
      context: ../..
      dockerfile: docker/docker-files/locust/Dockerfile.locust
    volumes:
      - ../../tests/load/:/mnt/locust/
    command: -f /mnt/locust --class-picker --worker --master-host locust_master
