version: '3'

services:
  locust_master_get:
    build:
      context: ../..
      dockerfile: docker/docker-files/locust/Dockerfile.locust
    volumes:
      - ../../tests/load/:/mnt/locust/
    ports:
     - 8089:8089
    command: -f /mnt/locust/get_test/locustfile_get_data_prs-psql.py --master -H http://locust_master_get:8089

  locust_worker_get:
    build:
      context: ../..
      dockerfile: docker/docker-files/locust/Dockerfile.locust
    volumes:
      - ../../tests/load/:/mnt/locust/
    command: -f /mnt/locust/get_test/locustfile_get_data_prs-psql.py --worker --master-host locust_master_get
