version: '3.9'

services:
  tags_all:
    hostname: tags_all
    build:
      context: ../..
      dockerfile: docker/docker-files/tags/Dockerfile.tags.all

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - 80:80

    volumes:
      - ./logs/tags.all/api_crud/:/usr/src/tags_api_crud/log/:rw
      - ./logs/tags.all/model_crud/:/usr/src/tags_model_crud/log/:rw
