version: '3.9'

services:
  data_storages_all:
    hostname: dataStorages_all
    build:
      context: ../..
      dockerfile: docker/docker-files/dataStorages/Dockerfile.dataStorages.all

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - 82:82

    volumes:
      - ./logs/dataStorages.all/api_crud/:/usr/src/dataStorages_api_crud/log/:rw
      - ./logs/dataStorages.all/model_crud/:/usr/src/dataStorages_model_crud/log/:rw
      - ./logs/dataStorages.all/app_psql/:/usr/src/dataStorages_app_psql/log/:rw

  psql:
    hostname: psql
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
