version: '3.9'

services:
  psql_load_tests:
    hostname: ${HOST_POSTGRES}
    image: mpc/peresvet_postgresql:0.4-arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    volumes:
      - /home/prs/psql_load_tests:/var/lib/postgresql/data
