version: '3.9'

services:
  nginx:
      image: nginx:latest
      hostname: nginx
      ports:
        - ${HTTP_PORT}:${HTTP_PORT}
        - ${HTTPS_PORT}:${HTTPS_PORT}
      #restart: always
      volumes:
        - ${PWD}/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${PWD}/config/nginx/no_ssl/default.conf.template:/etc/nginx/templates/default.conf.template:rw,cached
      environment:
        HTTP_PORT: ${HTTP_PORT}
        HTTPS_PORT: ${HTTPS_PORT}
        TAGS_APP_API_HTTP_PORT: ${TAGS_APP_API_HTTP_PORT}
        TZ: ${TIME_ZONE}
      depends_on:
        - tags_load_tests
