version: '3.9'

services:
  nginx_all_svc_in_one:
      hostname: ${NGINX_HOST}
      image: mpc/peresvet_nginx:0.4-arm64
      ports:
        - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
        - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
      environment:
        NGINX_HOST: ${NGINX_HOST}
        NGINX_HTTP_PORT: ${NGINX_HTTP_PORT}
        NGINX_HTTPS_PORT: ${NGINX_HTTPS_PORT}

        PORT_ALERTS_API_CRUD: ${PORT_ALERTS_API_CRUD}
        HOST_ALERTS_API_CRUD: ${HOST_ALERTS_API_CRUD}
        PORT_ALERTS_APP_API: ${PORT_ALERTS_APP_API}
        HOST_ALERTS_APP_API: ${HOST_ALERTS_APP_API}
        HOST_ALERTS_ALL: ${HOST_ALERTS_ALL}

        # connectors
        PORT_CONNECTORS_API_CRUD: ${PORT_CONNECTORS_API_CRUD}
        HOST_CONNECTORS_API_CRUD: ${HOST_CONNECTORS_API_CRUD}
        PORT_CONNECTORS_APP: ${PORT_CONNECTORS_APP}
        HOST_CONNECTORS_APP: ${HOST_CONNECTORS_APP}
        HOST_CONNECTORS_ALL: ${HOST_CONNECTORS_ALL}

        # dataStorages
        PORT_DATASTORAGES_API_CRUD: ${PORT_DATASTORAGES_API_CRUD}
        HOST_DATASTORAGES_API_CRUD: ${HOST_DATASTORAGES_API_CRUD}
        HOST_DATASTORAGES_ALL: ${HOST_DATASTORAGES_ALL}

        # methods
        PORT_METHODS_API_CRUD: ${PORT_METHODS_API_CRUD}
        HOST_METHODS_API_CRUD: ${HOST_METHODS_API_CRUD}
        HOST_METHODS_ALL: ${HOST_METHODS_ALL}

        # objects
        PORT_OBJECTS_API_CRUD: ${PORT_OBJECTS_API_CRUD}
        HOST_OBJECTS_API_CRUD: ${HOST_OBJECTS_API_CRUD}
        HOST_OBJECTS_ALL: ${HOST_OBJECTS_ALL}

        # tags
        PORT_TAGS_API_CRUD: ${PORT_TAGS_API_CRUD}
        HOST_TAGS_API_CRUD: ${HOST_TAGS_API_CRUD}
        PORT_TAGS_APP_API: ${PORT_TAGS_APP_API}
        HOST_TAGS_APP_API: ${HOST_TAGS_APP_API}
        HOST_TAGS_ALL: ${HOST_TAGS_ALL}

        # schedules
        PORT_SCHEDULES_API_CRUD: ${PORT_SCHEDULES_API_CRUD}
        HOST_SCHEDULES_API_CRUD: ${HOST_SCHEDULES_API_CRUD}
        HOST_SCHEDULES_ALL: ${HOST_SCHEDULES_ALL}

        #grafana
        PORT_GRAFANA: ${PORT_GRAFANA}
        HOST_GRAFANA: ${HOST_GRAFANA}

        TZ: ${TIME_ZONE}
      depends_on:
        - all_svc
