version: "3.8"
services:
  grafana:
    build:
      context: ../..
      dockerfile: docker/docker-files/grafana/Dockerfile.grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
