version: '3.9'

services:
  alerts_prepare_load_tests:
    hostname: alerts_prepare_load_tests
    build:
      context: ../..
      dockerfile: docker/docker-files/alerts/Dockerfile.alerts.prepare_load_tests

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - 80:80
      - 81:81

    volumes:
      - ./logs/alerts.all.load_tests/api_crud/:/usr/src/alerts_api_crud/log/:rw
      - ./logs/alerts.all.load_tests/model_crud/:/usr/src/alerts_model_crud/log/:rw
      - ./logs/alerts.all.load_tests/app/:/usr/src/alerts_app/log/:rw
      - ./logs/alerts.all.load_tests/app_api/:/usr/src/alerts_app_api/log/:rw
