version: '3.9'

services:
  ldap:
    container_name: ldap
    build:
      context: ../docker-files/ldap
      dockerfile: Dockerfile.ldap

    environment:
      TZ: ${TIME_ZONE}
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
    ports:
      - 389:389
