version: '3.9'

services:
  tags_load_tests:
    hostname: tags_load_tests
    build:
      context: ../..
      dockerfile: docker/docker-files/tags/Dockerfile.tags.load_tests.ssl

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - 443:443

    volumes:
      - ./logs/tags.all.load_tests/app/:/usr/src/tags_app/log/:rw
      - ./logs/tags.all.load_tests/app_api/:/usr/src/tags_app_api/log/:rw
