version: '3.9'

services:
  ldap:
    hostname: ${LDAP_HOST}
    image: mpc/peresvet_ldap:0.4-arm64

    environment:
      TZ: ${TIME_ZONE}
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
    ports:
      - ${LDAP_PORT}:${LDAP_PORT}
